gen2hdf5: gen2hdf5.o
	g++ -o gen2hdf5 gen2hdf5.o -lsz -lhdf5 -L /nfs/team151/software/hdf5/hdf5-1.8.17-linux-centos6-x86_64-gcc447-shared/lib
gen2hdf5.o: gen2hdf5.cpp
	g++ -o gen2hdf5.o -c gen2hdf5.cpp -I /nfs/team151/software/hdf5/hdf5-1.8.17-linux-centos6-x86_64-gcc447-shared/include 
